development:
   adapter: mysql
   database: crm_agenda
   username: root
   password:
   pool: 5
   timeout: 5000

test:
   adapter: mysql
   database: crm_agenda
   username: root
   password:
   pool: 5
   timeout: 5000

production:
   adapter: mysql
   database: crm_agenda
   username: root
   password:
   # database: inovare_vprestige
   # username: inovare_vprestig
   # password: pianista1987
   pool: 5
   timeout: 5000
